package org.client;

import org.springframework.stereotype.Component;

import java.util.concurrent.atomic.AtomicInteger;

/**
 *
 * Implements @IClient.
 * Contains information about client Country/State/City.
 * id is autogenerated to distinguish amongst similar clients.
 * {@code @Author} - Tal Greenblat
 */
@Component
public class Client implements IClient{
    private static final AtomicInteger count = new AtomicInteger(0);

    private final int id;
    private final String country;
    private final String state;
    private final String city;

    public Client (String country, String state, String city) {
        this.country = country;
        this.state = state;
        this.city = city;
        this.id = count.incrementAndGet();
    }

    @Override
    public String getCountry() {
        return country;
    }

    @Override
    public String getState() {
        return state;
    }

    @Override
    public String getCity() {
        return city;
    }

    public int getId(){
        return this.id;
    }

    @Override
    public String toString(){
        return "Client id: " +
                getId() +
                " Country: " +
                getCountry() +
                " State: " +
                getState() +
                " City: " +
                getCity();

    }
}
